In [3]:
import numpy as np
import pandas as pd
import sys, os


mypath                  = "/home/oline/Documents/UiO/FYS3150/FYS3150/Project_4/Py_Scripts/Results/4B/"

def read_files(path):  
    N, E, E2, M, M2, Abs_M, Chi, CV = [],[],[],[],[],[],[], []
    for filename in os.listdir(path):
        with open(path + filename, 'r') as infile:
            lines = infile.readlines()[2:]
            for line in lines:
                line = line.split()
                N.append(float(line[0]))
                E.append(float(line[1]))
                E2.append(float(line[2]))
                M.append(float(line[3]))
                M2.append(float(line[4]))
                Abs_M.append(float(line[5]))
                Chi.append(float(line[6]))
                CV.append(float(line[7]))
    df = pd.DataFrame({"N": N, "E": E, "E2": E2, "M": M, "M2": M2, "Abs_M": Abs_M, "Chi": Chi, "CV": CV})
    return df

Data = read_files(mypath)
analytical_values = np.load('analytical_values.npy')

In [4]:
Data

N        E       E2         M       M2    Abs_M        Chi  \
0       10000.0 -7.92240  63.3792  3.522400  15.8568  3.96720   3.449500   
1       10000.0 -7.95520  63.6416 -3.978600  15.9124  3.97860   0.083142   
2       10000.0 -7.94240  63.5392 -0.549400  15.8900  3.97380  15.588200   
3       10000.0 -7.93760  63.5008  3.968800  15.8816  3.97200   0.130227   
4       10000.0 -7.94320  63.5456 -3.820400  15.8920  3.97440   1.296540   
5       10000.0 -7.95120  63.6096 -0.493000  15.9052  3.97700  15.662200   
6       10000.0 -7.94720  63.5776  3.577000  15.8988  3.97580   3.103870   
7       10000.0 -7.94960  63.5968 -3.976800  15.9032  3.97680   0.088262   
8       10000.0 -7.94560  63.5648  2.567800  15.8964  3.97540   9.302800   
9       10000.0 -7.93440  63.4752 -2.393000  15.8764  3.97100  10.150000   
10     100000.0 -7.94672  63.5738  0.781800  15.8980  3.97564  15.286800   
11     100000.0 -7.94024  63.5219 -0.344660  15.8870  3.97338  15.768200   
12     100000.0 -7.94000  63.5200 -0.595540  15.8866  3.97330  15.531900   
13     100000.0 -7.94208  63.5366  0.266280  15.8900  3.97396  15.819100   
14     100000.0 -7.94976  63.5981 -2.021920  15.9030  3.97660  11.814800   
15     100000.0 -7.94808  63.5846 -2.169040  15.9001  3.97600  11.195300   
16     100000.0 -7.94912  63.5930  1.201380  15.9020  3.97642  14.458600   
17     100000.0 -7.94216  63.5373  0.120580  15.8904  3.97414  15.875900   
18     100000.0 -7.94408  63.5526  0.709440  15.8934  3.97468  15.390100   
19     100000.0 -7.94536  63.5629  0.854040  15.8955  3.97508  15.166100   
20    1000000.0 -7.94536  63.5629  0.376724  15.8956  3.97512  15.753700   
21    1000000.0 -7.94490  63.5594  0.206114  15.8949  3.97498  15.852400   
22    1000000.0 -7.94434  63.5548  0.199454  15.8939  3.97479  15.854200   
23    1000000.0 -7.94302  63.5441  0.211568  15.8916  3.97430  15.846900   
24    1000000.0 -7.94382  63.5505 -0.177716  15.8930  3.97462  15.861500   
25    1000000.0 -7.94427  63.5542  0.507010  15.8938  3.97476  15.636700   
26    1000000.0 -7.94380  63.5505  0.374748  15.8931  3.97465  15.752700   
27    1000000.0 -7.94579  63.5665 -0.162794  15.8964  3.97531  15.869900   
28    1000000.0 -7.94487  63.5590  0.598454  15.8948  3.97494  15.536600   
29    1000000.0 -7.94482  63.5585  0.125746  15.8947  3.97494  15.878900   
30   10000000.0 -7.94436  63.5549  0.184843  15.8939  3.97479  15.859800   
31   10000000.0 -7.94429  63.5543 -0.221683  15.8939  3.97478  15.844700   
32   10000000.0 -7.94446  63.5557  0.097536  15.8941  3.97482  15.884600   
33   10000000.0 -7.94390  63.5512 -0.107338  15.8931  3.97462  15.881600   
34   10000000.0 -7.94417  63.5534  0.076902  15.8936  3.97472  15.887700   
35   10000000.0 -7.94406  63.5525  0.012137  15.8934  3.97469  15.893300   
36   10000000.0 -7.94410  63.5528  0.130024  15.8935  3.97469  15.876600   
37   10000000.0 -7.94411  63.5529  0.091480  15.8935  3.97471  15.885200   
38   10000000.0 -7.94343  63.5474  0.000611  15.8923  3.97445  15.892300   
39   10000000.0 -7.94358  63.5486 -0.142043  15.8926  3.97452  15.872400   
40  100000000.0 -7.94401  63.5521  0.008710  15.8934  3.97467  15.893300   
41  100000000.0 -7.94407  63.5526  0.046919  15.8934  3.97469  15.891200   
42  100000000.0 -7.94398  63.5518 -0.018769  15.8933  3.97466  15.892900   
43  100000000.0 -7.94399  63.5519  0.016554  15.8933  3.97466  15.893000   
44  100000000.0 -7.94414  63.5531  0.007792  15.8936  3.97472  15.893500   
45  100000000.0 -7.94407  63.5526 -0.037262  15.8935  3.97469  15.892100   
46  100000000.0 -7.94407  63.5525 -0.003625  15.8934  3.97469  15.893400   
47  100000000.0 -7.94401  63.5521  0.040217  15.8933  3.97467  15.891700   
48  100000000.0 -7.94388  63.5510  0.024975  15.8931  3.97462  15.892500   
49  100000000.0 -7.94398  63.5519  0.013775  15.8933  3.97466  15.893100   

          CV  
0   0.614778  
1   0.356393  
2   0.457482  
3   0.495306  
4   0.451174  
5   0.388019  
6   0.419612  
7   0.400660  
8 

In [5]:
Data_10_4 = Data[(Data["N"] == 10000) & (Data['E'] != 0)]
Data_10_5 = Data[(Data["N"] == 100000) & (Data['E'] != 0)]
Data_10_6 = Data[(Data["N"] == 1000000) & (Data['E'] != 0)]
Data_10_7 = Data[(Data["N"] == 10000000) & (Data['E'] != 0)]
Data_10_8 = Data[(Data["N"] == 100000000) & (Data['E'] != 0)]

In [6]:
i = 0
N = np.array([Data_10_4.mean()[i], Data_10_5.mean()[i],  Data_10_6.mean()[i],  Data_10_7.mean()[i],  Data_10_8.mean()[i]])

i = 1
E = np.array([Data_10_4.mean()[i], Data_10_5.mean()[i],  Data_10_6.mean()[i],  Data_10_7.mean()[i],  Data_10_8.mean()[i]])

i = 2
E2 = np.array([Data_10_4.mean()[i], Data_10_5.mean()[i],  Data_10_6.mean()[i],  Data_10_7.mean()[i],  Data_10_8.mean()[i]])

i = 3
M = np.array([Data_10_4.mean()[i], Data_10_5.mean()[i],  Data_10_6.mean()[i],  Data_10_7.mean()[i],  Data_10_8.mean()[i]])

i = 4
M2 = np.array([Data_10_4.mean()[i], Data_10_5.mean()[i],  Data_10_6.mean()[i],  Data_10_7.mean()[i],  Data_10_8.mean()[i]])

i = 5
Abs_M = np.array([Data_10_4.mean()[i], Data_10_5.mean()[i],  Data_10_6.mean()[i],  Data_10_7.mean()[i],  Data_10_8.mean()[i]])

i = 6
Chi = np.array([Data_10_4.mean()[i], Data_10_5.mean()[i],  Data_10_6.mean()[i],  Data_10_7.mean()[i],  Data_10_8.mean()[i]])

i = 7
CV = np.array([Data_10_4.mean()[i], Data_10_5.mean()[i],  Data_10_6.mean()[i],  Data_10_7.mean()[i],  Data_10_8.mean()[i]])

In [7]:
Desimals = 4

In [8]:
N

array([1.e+04, 1.e+05, 1.e+06, 1.e+07, 1.e+08])

In [9]:
print(np.round(E, Desimals))

[-7.9429 -7.9448 -7.9445 -7.944  -7.944 ]


In [10]:
print(np.round(E2, Desimals))

[63.543  63.5581 63.556  63.5524 63.5522]


In [11]:
print(np.round(M, Desimals))

[-0.1575 -0.1198  0.2259  0.0122  0.0099]


In [12]:
print(np.round(M2, Desimals))

[15.8913 15.8946 15.8942 15.8934 15.8934]


In [13]:
print(np.round(Abs_M, Desimals))

[3.9742 3.9749 3.9748 3.9747 3.9747]


In [14]:
print(np.round(Chi, Desimals))

[ 5.8855 14.6307 15.7844 15.8778 15.8927]


In [15]:
print(np.round(CV, Desimals))

[0.4536 0.4389 0.441  0.4445 0.4447]


In [16]:
with open('Results/4B/Average_results', 'w') as outfile:
    outfile.write('N        E  E2  M  M2   Abs_M  Chi  CV\n')
    outfile.write('Analytical values ' + str(np.round(analytical_values , 3))[1:-1]+'\n')
    for i in range(5):
        outfile.write(str(np.round(N[i], Desimals)) + '             ' + str(np.round(E[i], Desimals))+'    ' + str(np.round(E2[i], Desimals)) + '    ' + str(np.round(M[i], Desimals)) + '    ' + str(np.round(M2[i], Desimals)) + '    ' + str(np.round(Abs_M[i], Desimals)) + '   ' + str(np.round(Chi[i], Desimals))+ '    ' + str(np.round(CV[i], Desimals)) + '\n')

In [17]:
str(N[0])

'10000.0'