In [53]:
import numpy as np
import pandas as pd
import sys, os


mypath                  = "/home/oline/Documents/UiO/FYS3150/FYS3150/Project_4/Py_Scripts/Results/4B/"

def read_files(path):  
    N, E, E2, M, M2, Abs_M, Chi, CV = [],[],[],[],[],[],[], []
    for filename in os.listdir(path):
        with open(path + filename, 'r') as infile:
            lines = infile.readlines()[2:]
            for line in lines:
                line = line.split()
                N.append(float(line[0]))
                E.append(float(line[1]))
                E2.append(float(line[2]))
                M.append(float(line[3]))
                M2.append(float(line[4]))
                Abs_M.append(float(line[5]))
                Chi.append(float(line[6]))
                CV.append(float(line[7]))
    df = pd.DataFrame({"N": N, "E": E, "E2": E2, "M": M, "M2": M2, "Abs_M": Abs_M, "Chi": Chi, "CV": CV})
    return df

Data = read_files(mypath)
analytical_values = np.load('analytical_values.npy')

In [54]:
analytical_values[0] = analytical_values[0]/4
analytical_values[1] = analytical_values[1]/4
analytical_values[2] = analytical_values[2]/4
analytical_values[3] = analytical_values[3]/4
analytical_values[4] = analytical_values[4]/4
analytical_values[5] = analytical_values[5]/4
analytical_values[6] = analytical_values[6]/4

In [55]:
Data_10_4 = Data[(Data["N"] == 10000) & (Data['E'] != 0)]
Data_10_5 = Data[(Data["N"] == 100000) & (Data['E'] != 0)]
Data_10_6 = Data[(Data["N"] == 1000000) & (Data['E'] != 0)]
Data_10_7 = Data[(Data["N"] == 10000000) & (Data['E'] != 0)]
Data_10_8 = Data[(Data["N"] == 100000000) & (Data['E'] != 0)]

In [56]:
analytical_values[4]

0.997991155277454

In [57]:
i = 0
N = np.array([Data_10_4.mean()[i], Data_10_5.mean()[i],  Data_10_6.mean()[i],  Data_10_7.mean()[i],  Data_10_8.mean()[i]])

i = 1
E = np.array([Data_10_4.mean()[i], Data_10_5.mean()[i],  Data_10_6.mean()[i],  Data_10_7.mean()[i],  Data_10_8.mean()[i]])

i = 2
E2 = np.array([Data_10_4.mean()[i], Data_10_5.mean()[i],  Data_10_6.mean()[i],  Data_10_7.mean()[i],  Data_10_8.mean()[i]])

i = 3
M = np.array([Data_10_4.mean()[i], Data_10_5.mean()[i],  Data_10_6.mean()[i],  Data_10_7.mean()[i],  Data_10_8.mean()[i]])

i = 4
M2 = np.array([Data_10_4.mean()[i], Data_10_5.mean()[i],  Data_10_6.mean()[i],  Data_10_7.mean()[i],  Data_10_8.mean()[i]])

i = 5
Abs_M = np.array([Data_10_4.mean()[i], Data_10_5.mean()[i],  Data_10_6.mean()[i],  Data_10_7.mean()[i],  Data_10_8.mean()[i]])

i = 6
Chi = np.array([Data_10_4.mean()[i], Data_10_5.mean()[i],  Data_10_6.mean()[i],  Data_10_7.mean()[i],  Data_10_8.mean()[i]])

i = 7
CV = np.array([Data_10_4.mean()[i], Data_10_5.mean()[i],  Data_10_6.mean()[i],  Data_10_7.mean()[i],  Data_10_8.mean()[i]])

In [58]:
Desimals = 4

In [59]:
N

array([1.e+04, 1.e+05, 1.e+06, 1.e+07, 1.e+08])

In [60]:
print(np.round(E, Desimals))

[-1.9974 -1.9967 -1.9958 -1.996  -1.996 ]


In [61]:
print(np.round(E2, Desimals))

[15.9793 15.9739 15.9667 15.968  15.9678]


In [62]:
print(np.round(M, Desimals))

[ 0.6353 -0.0309 -0.0351 -0.0037 -0.0015]


In [63]:
print(np.round(M2, Desimals))

[3.9958 3.9946 3.9931 3.9933 3.9933]


In [64]:
print(np.round(Abs_M, Desimals))

[0.9992 0.9989 0.9986 0.9987 0.9987]


In [65]:
print(np.round(Chi, Desimals))

[0.0207 0.026  0.0332 0.032  0.0321]


In [66]:
print(np.round(CV, Desimals))

[1.7822 3.7958 3.9452 3.9897 3.9931]


In [67]:
with open('Results/4B/Average_results.txt', 'w') as outfile:
    outfile.write('N        E  E2  M  M2   Abs_M  Chi  CV\n')
    for i in range(5):
        outfile.write(str(np.round(N[i], Desimals)) + '             ' + str(np.round(E[i], Desimals))+'    ' + str(np.round(E2[i], Desimals)) + '    ' + str(np.round(M[i], Desimals)) + '    ' + str(np.round(M2[i], Desimals)) + '    ' + str(np.round(Abs_M[i], Desimals)) + '   ' + str(np.round(Chi[i], Desimals))+ '    ' + str(np.round(CV[i], Desimals)) + '\n')
    outfile.write('\n')
    outfile.write('Analytical values ' + str(np.round(analytical_values , 4))[1:-1]+'\n')
    

In [68]:
str(N[0])

'10000.0'

In [69]:
with open('Results/4B/Average_results_tex.txt', 'w') as outfile:
    outfile.write('\textbf{N}  \textbf{E}  \textbf{E2}  \textbf{M}  \textbf{M2}   \textbf{Abs_M}  \textbf{Chi}  \textbf{C}$_V$ \n')
    for i in range(5):
        outfile.write(str(np.round(N[i], Desimals)) + '   &          ' + str(np.round(E[i], Desimals))+'   & ' + str(np.round(E2[i], Desimals)) + '  &  ' + str(np.round(M[i], Desimals)) + ' &   ' + str(np.round(M2[i], Desimals)) + ' &   ' + str(np.round(Abs_M[i], Desimals)) + '&   ' + str(np.round(Chi[i], Desimals))+ ' &   ' + str(np.round(CV[i], Desimals)) + '\\\\ \n')
    outfile.write('\n')
    outfile.write('Analytical values ' + str(np.round(analytical_values , 4))[1:-1]+'\n')
     