In [108]:
import numpy as np
import pandas as pd
import sys, os


mypath                  = "/home/oline/Documents/UiO/FYS3150/FYS3150/Project_4/Py_Scripts/Results/4B/"

def read_files(path):  
    N, E, E2, M, M2, Abs_M, Chi, CV = [],[],[],[],[],[],[], []
    for filename in os.listdir(path):
        with open(path + filename, 'r') as infile:
            lines = infile.readlines()[2:]
            for line in lines:
                line = line.split()
                N.append(float(line[0]))
                E.append(float(line[1]))
                E2.append(float(line[2]))
                M.append(float(line[3]))
                M2.append(float(line[4]))
                Abs_M.append(float(line[5]))
                Chi.append(float(line[6]))
                CV.append(float(line[7]))
    df = pd.DataFrame({"N": N, "E": E, "E2": E2, "M": M, "M2": M2, "Abs_M": Abs_M, "Chi": Chi, "CV": CV})
    return df

Data = read_files(mypath)
analytical_values = np.load('analytical_values.npy')

In [109]:
analytical_values[0] = analytical_values[0]/4
analytical_values[1] = analytical_values[1]/4
analytical_values[6] = analytical_values[6]/4
analytical_values[5] = analytical_values[5]/4

In [110]:
Data_10_4 = Data[(Data["N"] == 10000) & (Data['E'] != 0)]
Data_10_5 = Data[(Data["N"] == 100000) & (Data['E'] != 0)]
Data_10_6 = Data[(Data["N"] == 1000000) & (Data['E'] != 0)]
Data_10_7 = Data[(Data["N"] == 10000000) & (Data['E'] != 0)]
Data_10_8 = Data[(Data["N"] == 100000000) & (Data['E'] != 0)]

In [111]:
i = 0
N = np.array([Data_10_4.mean()[i], Data_10_5.mean()[i],  Data_10_6.mean()[i],  Data_10_7.mean()[i],  Data_10_8.mean()[i]])

i = 1
E = np.array([Data_10_4.mean()[i], Data_10_5.mean()[i],  Data_10_6.mean()[i],  Data_10_7.mean()[i],  Data_10_8.mean()[i]])

i = 2
E2 = np.array([Data_10_4.mean()[i], Data_10_5.mean()[i],  Data_10_6.mean()[i],  Data_10_7.mean()[i],  Data_10_8.mean()[i]])

i = 3
M = np.array([Data_10_4.mean()[i], Data_10_5.mean()[i],  Data_10_6.mean()[i],  Data_10_7.mean()[i],  Data_10_8.mean()[i]])

i = 4
M2 = np.array([Data_10_4.mean()[i], Data_10_5.mean()[i],  Data_10_6.mean()[i],  Data_10_7.mean()[i],  Data_10_8.mean()[i]])

i = 5
Abs_M = np.array([Data_10_4.mean()[i], Data_10_5.mean()[i],  Data_10_6.mean()[i],  Data_10_7.mean()[i],  Data_10_8.mean()[i]])

i = 6
Chi = np.array([Data_10_4.mean()[i], Data_10_5.mean()[i],  Data_10_6.mean()[i],  Data_10_7.mean()[i],  Data_10_8.mean()[i]])

i = 7
CV = np.array([Data_10_4.mean()[i], Data_10_5.mean()[i],  Data_10_6.mean()[i],  Data_10_7.mean()[i],  Data_10_8.mean()[i]])

In [112]:
Desimals = 4

In [113]:
N

array([1.e+04, 1.e+05, 1.e+06, 1.e+07, 1.e+08])

In [114]:
print(np.round(E, Desimals))

[-1.9952 -1.9963 -1.9959 -1.996  -1.996 ]


In [115]:
print(np.round(E2, Desimals))

[15.9617 15.9701 15.9674 15.968  15.9678]


In [116]:
print(np.round(M, Desimals))

[ 0.8206 -0.5715 -0.1322  0.0064  0.0201]


In [117]:
print(np.round(M2, Desimals))

[15.968  15.9751 15.9729 15.9733 15.9732]


In [118]:
print(np.round(Abs_M, Desimals))

[3.9936 3.995  3.9946 3.9947 3.9946]


In [119]:
print(np.round(Chi, Desimals))

[0.0381 0.0298 0.0325 0.032  0.0321]


In [120]:
print(np.round(CV, Desimals))

[1.6071 3.5324 3.9499 3.9908 3.9928]


In [121]:
with open('Results/4B/Average_results.txt', 'w') as outfile:
    outfile.write('N        E  E2  M  M2   Abs_M  Chi  CV\n')
    for i in range(5):
        outfile.write(str(np.round(N[i], Desimals)) + '             ' + str(np.round(E[i], Desimals))+'    ' + str(np.round(E2[i], Desimals)) + '    ' + str(np.round(M[i], Desimals)) + '    ' + str(np.round(M2[i], Desimals)) + '    ' + str(np.round(Abs_M[i], Desimals)) + '   ' + str(np.round(Chi[i], Desimals))+ '    ' + str(np.round(CV[i], Desimals)) + '\n')
    outfile.write('\n')
    outfile.write('Analytical values ' + str(np.round(analytical_values , 4))[1:-1]+'\n')
    

In [122]:
str(N[0])

'10000.0'

In [123]:
with open('Results/4B/Average_results_tex.txt', 'w') as outfile:
    outfile.write('\textbf{N}  \textbf{E}  \textbf{E2}  \textbf{M}  \textbf{M2}   \textbf{Abs_M}  \textbf{Chi}  \textbf{C}$_V$ \n')
    for i in range(5):
        outfile.write(str(np.round(N[i], Desimals)) + '   &          ' + str(np.round(E[i], Desimals))+'   & ' + str(np.round(E2[i], Desimals)) + '  &  ' + str(np.round(M[i], Desimals)) + ' &   ' + str(np.round(M2[i], Desimals)) + ' &   ' + str(np.round(Abs_M[i], Desimals)) + '&   ' + str(np.round(Chi[i], Desimals))+ ' &   ' + str(np.round(CV[i], Desimals)) + '\\\\ \n')
    outfile.write('\n')
    outfile.write('Analytical values ' + str(np.round(analytical_values , 4))[1:-1]+'\n')
     