In [118]:
import numpy as np
import pandas as pd
import sys, os


mypath                  = "/home/oline/Documents/UiO/FYS3150/FYS3150/Project_4/Py_Scripts/Results/4B/"

def read_files(path):  
    N, E, E2, M, M2, Abs_M, Chi, CV = [],[],[],[],[],[],[], []
    for filename in os.listdir(path):
        with open(path + filename, 'r') as infile:
            lines = infile.readlines()[2:]
            for line in lines:
                line = line.split()
                N.append(float(line[0]))
                E.append(float(line[1]))
                E2.append(float(line[2]))
                M.append(float(line[3]))
                M2.append(float(line[4]))
                Abs_M.append(float(line[5]))
                Chi.append(float(line[6]))
                CV.append(float(line[7]))
    df = pd.DataFrame({"N": N, "E": E, "E2": E2, "M": M, "M2": M2, "Abs_M": Abs_M, "Chi": Chi, "CV": CV})
    return df

Data = read_files(mypath)
analytical_values = np.load('analytical_values.npy')

In [54]:
Data

N        E       E2         M       M2    Abs_M        Chi  \
0       10000.0 -7.92960  63.4368  3.972400  15.8744  3.97240   0.094438   
1       10000.0 -7.94960  63.5968 -3.977400  15.9044  3.97740   0.084689   
2       10000.0  0.00000   0.0000  0.000000   0.0000  0.00000   0.000000   
3       10000.0 -7.94560  63.5648  3.976400  15.8984  3.97640   0.086643   
4       10000.0 -7.94480  63.5584  3.976200  15.8972  3.97620   0.087034   
5       10000.0  0.00000   0.0000  0.000000   0.0000  0.00000   0.000000   
6       10000.0  0.00000   0.0000  0.000000   0.0000  0.00000   0.000000   
7       10000.0 -7.94720  63.5776 -3.976800  15.9008  3.97680   0.085862   
8       10000.0 -7.95200  63.6160 -3.978000  15.9080  3.97800   0.083516   
9       10000.0 -7.96000  63.6800  3.980000  15.9200  3.98000   0.079600   
10     100000.0 -7.94272  63.5418 -3.975680  15.8941  3.97568   0.088049   
11     100000.0 -7.94624  63.5699 -3.976560  15.8994  3.97656   0.086331   
12     100000.0 -7.95144  63.6115 -3.977860  15.9072  3.97786   0.083790   
13     100000.0 -7.95232  63.6186 -3.978080  15.9085  3.97808   0.083360   
14     100000.0 -7.95224  63.6179 -3.978060  15.9084  3.97806   0.083399   
15     100000.0  0.00000   0.0000  0.000000   0.0000  0.00000   0.000000   
16     100000.0 -7.94840  63.5872 -3.977100  15.9026  3.97710   0.085276   
17     100000.0  0.00000   0.0000  0.000000   0.0000  0.00000   0.000000   
18     100000.0 -7.94728  63.5782 -3.976820  15.9009  3.97682   0.085823   
19     100000.0 -7.94872  63.5910 -3.977180  15.9032  3.97718   0.085199   
20    1000000.0  0.00000   0.0000  0.000000   0.0000  0.00000   0.000000   
21    1000000.0  0.00000   0.0000  0.000000   0.0000  0.00000   0.000000   
22    1000000.0  0.00000   0.0000  0.000000   0.0000  0.00000   0.000000   
23    1000000.0  0.00000   0.0000  0.000000   0.0000  0.00000   0.000000   
24    1000000.0  0.00000   0.0000  0.000000   0.0000  0.00000   0.000000   
25    1000000.0  0.00000   0.0000  0.000000   0.0000  0.00000   0.000000   
26    1000000.0 -7.94944  63.5955  3.977360  15.9042  3.97736   0.084767   
27    1000000.0 -7.94871  63.5897 -3.977180  15.9031  3.97718   0.085123   
28    1000000.0  0.00000   0.0000  0.000000   0.0000  0.00000   0.000000   
29    1000000.0 -7.94930  63.5944 -3.977320  15.9039  3.97732   0.084838   
30   10000000.0 -7.94912  63.5930  0.859994  15.9037  3.97728  15.164100   
31   10000000.0 -7.94929  63.5943 -1.584310  15.9039  3.97732  13.393900   
32   10000000.0  0.00000   0.0000  0.000000   0.0000  0.00000   0.000000   
33   10000000.0  0.00000   0.0000  0.000000   0.0000  0.00000   0.000000   
34   10000000.0  0.00000   0.0000  0.000000   0.0000  0.00000   0.000000   
35   10000000.0 -7.94958  63.5967 -0.256130  15.9044  3.97740  15.838800   
36   10000000.0 -7.94945  63.5956 -0.203861  15.9042  3.97736  15.862600   
37   10000000.0 -7.94960  63.5968 -3.977400  15.9044  3.97740   0.084690   
38   10000000.0 -7.94937  63.5949  1.312510  15.9041  3.97734  14.181400   
39   10000000.0 -7.94951  63.5961  3.136000  15.9043  3.97738   6.069760   
40  100000000.0 -7.94940  63.5952 -2.002040  15.9041  3.97735  11.895900   
41  100000000.0 -7.94934  63.5947 -2.539160  15.9040  3.97734   9.456660   
42  100000000.0  0.00000   0.0000  0.000000   0.0000  0.00000   0.000000   
43  100000000.0 -7.94943  63.5955  1.798280  15.9041  3.97736  12.670300   
44  100000000.0 -7.94952  63.5961  0.296858  15.9043  3.97738  15.816100   
45  100000000.0 -7.94938  63.5951  0.463573  15.9041  3.97734  15.689200   
46  100000000.0 -7.94939  63.5951 -1.213160  15.9041  3.97735  14.432300   
47  100000000.0 -7.94941  63.5953 -0.169695  15.9041  3.97735  15.875300   
48  100000000.0 -7.94933  63.5947  0.842337  15.9040  3.97733  15.194500   
49  100000000.0 -7.94935  63.5948  2.282990  15.9040  3.97734  10.692000   

          CV  
0   0.558244  
1   0.400660  
2   0.000000  
3   0.432241  
4   0.438553  
5   0.000000  
6   0.000000  
7   0.419612  
8 

In [58]:
Data_10_4 = Data[(Data["N"] == 10000) & (Data['E'] != 0)]
Data_10_5 = Data[(Data["N"] == 100000) & (Data['E'] != 0)]
Data_10_6 = Data[(Data["N"] == 1000000) & (Data['E'] != 0)]
Data_10_7 = Data[(Data["N"] == 10000000) & (Data['E'] != 0)]
Data_10_8 = Data[(Data["N"] == 100000000) & (Data['E'] != 0)]

In [130]:
i = 0
N = np.array([Data_10_4.mean()[i], Data_10_5.mean()[i],  Data_10_6.mean()[i],  Data_10_7.mean()[i],  Data_10_8.mean()[i]])

i = 1
E = np.array([Data_10_4.mean()[i], Data_10_5.mean()[i],  Data_10_6.mean()[i],  Data_10_7.mean()[i],  Data_10_8.mean()[i]])

i = 2
E2 = np.array([Data_10_4.mean()[i], Data_10_5.mean()[i],  Data_10_6.mean()[i],  Data_10_7.mean()[i],  Data_10_8.mean()[i]])

i = 3
M = np.array([Data_10_4.mean()[i], Data_10_5.mean()[i],  Data_10_6.mean()[i],  Data_10_7.mean()[i],  Data_10_8.mean()[i]])

i = 4
M2 = np.array([Data_10_4.mean()[i], Data_10_5.mean()[i],  Data_10_6.mean()[i],  Data_10_7.mean()[i],  Data_10_8.mean()[i]])

i = 5
Abs_M = np.array([Data_10_4.mean()[i], Data_10_5.mean()[i],  Data_10_6.mean()[i],  Data_10_7.mean()[i],  Data_10_8.mean()[i]])

i = 6
Chi = np.array([Data_10_4.mean()[i], Data_10_5.mean()[i],  Data_10_6.mean()[i],  Data_10_7.mean()[i],  Data_10_8.mean()[i]])

i = 7
CV = np.array([Data_10_4.mean()[i], Data_10_5.mean()[i],  Data_10_6.mean()[i],  Data_10_7.mean()[i],  Data_10_8.mean()[i]])

In [131]:
Desimals = 4

In [132]:
N

array([1.e+04, 1.e+05, 1.e+06, 1.e+07, 1.e+08])

In [133]:
print(np.round(E, Desimals))

[-7.947  -7.9487 -7.9492 -7.9494 -7.9494]


In [134]:
print(np.round(E2, Desimals))

[63.5758 63.5895 63.5932 63.5953 63.5952]


In [135]:
print(np.round(M, Desimals))

[ 0.5675 -3.9772 -1.3257 -0.1019 -0.0267]


In [136]:
print(np.round(M2, Desimals))

[15.9005 15.903  15.9037 15.9041 15.9041]


In [137]:
print(np.round(Abs_M, Desimals))

[3.9767 3.9772 3.9773 3.9774 3.9773]


In [138]:
print(np.round(Chi, Desimals))

[ 0.086   0.0852  0.0849 11.5136 13.5247]


In [139]:
print(np.round(CV, Desimals))

[0.4213 0.4082 0.4042 0.4021 0.4023]


In [156]:
with open('Results/4B/Average_results', 'w') as outfile:
    outfile.write('N        E  E2  M  M2   Abs_M  Chi  CV\n')
    outfile.write('Analytical values ' + str(np.round(analytical_values , 3))[1:-1]+'\n')
    for i in range(5):
        outfile.write(str(np.round(N[i], Desimals)) + '             ' + str(np.round(E[i], Desimals))+'    ' + str(np.round(E2[i], Desimals)) + '    ' + str(np.round(M[i], Desimals)) + '    ' + str(np.round(M2[i], Desimals)) + '    ' + str(np.round(Abs_M[i], Desimals)) + '   ' + str(np.round(Chi[i], Desimals))+ '    ' + str(np.round(CV[i], Desimals)) + '\n')

In [154]:
str(N[0])

'10000.0'